# Generated by Django 4.1.5 on 2023-01-31 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_product_order"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Vending_Machine",
            new_name="VendingMachine",
        ),
    ]
